export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT_SUCCESS';

// user profile
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// Payment
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS';
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE';
export const MAKE_PAYMENT_SUCCESS = 'MAKE_PAYMENT_SUCCESS';
export const MAKE_PAYMENT_FAILURE = 'MAKE_PAYMENT_FAILURE';

//Expenditure
export const FETCH_EXPENDITURES_REQUEST = 'FETCH_EXPENDITURES_REQUEST';
export const FETCH_EXPENDITURES_SUCCESS = 'FETCH_EXPENDITURES_SUCCESS';
export const FETCH_EXPENDITURES_FAILURE = 'FETCH_EXPENDITURES_FAILURE';
export const FETCH_EXPENDITURE_DETAIL_REQUEST = 'FETCH_EXPENDITURE_DETAIL_REQUEST';
export const FETCH_EXPENDITURE_DETAIL_SUCCESS = 'FETCH_EXPENDITURE_DETAIL_SUCCESS';
export const FETCH_EXPENDITURE_DETAIL_FAILURE = 'FETCH_EXPENDITURE_DETAIL_FAILURE';

// Admin action types
// User action types
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_USER_DETAIL_REQUEST = 'FETCH_USER_DETAIL_REQUEST';
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS';
export const FETCH_USER_DETAIL_FAILURE = 'FETCH_USER_DETAIL_FAILURE';

export const EDIT_USER_PROFILE_REQUEST = 'EDIT_USER_PROFILE_REQUEST';
export const EDIT_USER_PROFILE_SUCCESS = 'EDIT_USER_PROFILE_SUCCESS';
export const EDIT_USER_PROFILE_FAILURE = 'EDIT_USER_PROFILE_FAILURE';

export const EDIT_USER_STATUS_REQUEST = 'EDIT_USER_STATUS_REQUEST';
export const EDIT_USER_STATUS_SUCCESS = 'EDIT_USER_STATUS_SUCCESS';
export const EDIT_USER_STATUS_FAILURE = 'EDIT_USER_STATUS_FAILURE';

// Payment action types
export const FETCH_PENDING_PAYMENTS_REQUEST = 'FETCH_PENDING_PAYMENTS_REQUEST';
export const FETCH_PENDING_PAYMENTS_SUCCESS = 'FETCH_PENDING_PAYMENTS_SUCCESS';
export const FETCH_PENDING_PAYMENTS_FAILURE = 'FETCH_PENDING_PAYMENTS_FAILURE';

export const APPROVE_PAYMENT_REQUEST = 'APPROVE_PAYMENT_REQUEST';
export const APPROVE_PAYMENT_SUCCESS = 'APPROVE_PAYMENT_SUCCESS';
export const APPROVE_PAYMENT_FAILURE = 'APPROVE_PAYMENT_FAILURE';

export const REJECT_PAYMENT_REQUEST = 'REJECT_PAYMENT_REQUEST';
export const REJECT_PAYMENT_SUCCESS = 'REJECT_PAYMENT_SUCCESS';
export const REJECT_PAYMENT_FAILURE = 'REJECT_PAYMENT_FAILURE';

// Total money collected action types
export const FETCH_TOTAL_MONEY_REQUEST = 'FETCH_TOTAL_MONEY_REQUEST';
export const FETCH_TOTAL_MONEY_SUCCESS = 'FETCH_TOTAL_MONEY_SUCCESS';
export const FETCH_TOTAL_MONEY_FAILURE = 'FETCH_TOTAL_MONEY_FAILURE';

export const EDIT_TOTAL_MONEY_REQUEST = 'EDIT_TOTAL_MONEY_REQUEST';
export const EDIT_TOTAL_MONEY_SUCCESS = 'EDIT_TOTAL_MONEY_SUCCESS';
export const EDIT_TOTAL_MONEY_FAILURE = 'EDIT_TOTAL_MONEY_FAILURE';

// Announcement action types
export const POST_ANNOUNCEMENT_REQUEST = 'POST_ANNOUNCEMENT_REQUEST';
export const POST_ANNOUNCEMENT_SUCCESS = 'POST_ANNOUNCEMENT_SUCCESS';
export const POST_ANNOUNCEMENT_FAILURE = 'POST_ANNOUNCEMENT_FAILURE';

export const DOWNLOAD_USERS_CSV_REQUEST = "DOWNLOAD_USERS_CSV_REQUEST";
export const DOWNLOAD_USERS_CSV_SUCCESS = "DOWNLOAD_USERS_CSV_SUCCESS";
export const DOWNLOAD_USERS_CSV_FAILURE = "DOWNLOAD_USERS_CSV_FAILURE";

export const DOWNLOAD_PAYMENT_FILE_REQUEST = "DOWNLOAD_PAYMENT_FILE_REQUEST";
export const DOWNLOAD_PAYMENT_FILE_SUCCESS = "DOWNLOAD_PAYMENT_FILE_SUCCESS";
export const DOWNLOAD_PAYMENT_FILE_FAILURE = "DOWNLOAD_PAYMENT_FILE_FAILURE";


export const FETCH_ALL_PAYMENTS_REQUEST="FETCH_ALL_PAYMENTS_REQUEST"; 
export const FETCH_ALL_PAYMENTS_SUCCESS = "FETCH_ALL_PAYMENTS_SUCCESS";
export const FETCH_ALL_PAYMENTS_FAILURE="FETCH_ALL_PAYMENTS_FAILURE";

export const FETCH_PAYMENT_DETAIL_REQUEST="FETCH_PAYMENT_DETAIL_REQUEST";
export const FETCH_PAYMENT_DETAIL_SUCCESS="FETCH_PAYMENT_DETAIL_SUCCESS";
export const FETCH_PAYMENT_DETAIL_FAILURE="FETCH_PAYMENT_DETAIL_FAILURE";

export const FETCH_USER_PAYMENTS_REQUEST = "FETCH_USER_PAYMENTS_REQUEST";
export const FETCH_USER_PAYMENTS_SUCCESS = "FETCH_USER_PAYMENTS_SUCCESS";
export const FETCH_USER_PAYMENTS_FAILURE = "FETCH_USER_PAYMENTS_FAILURE";

export const FETCH_ADMIN_PROFILE_REQUEST = "FETCH_ADMIN_PROFILE_REQUEST";
export const FETCH_ADMIN_PROFILE_SUCCESS = "FETCH_ADMIN_PROFILE_SUCCESS";
export const FETCH_ADMIN_PROFILE_FAILURE = "FETCH_ADMIN_PROFILE_FAILURE";


// Announcements
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILURE = "FETCH_ANNOUNCEMENTS_FAILURE"

export const FETCH_ANNOUNCEMENT_DETAIL_SUCCESS = 'FETCH_ANNOUNCEMENT_DETAIL_SUCCESS';
export const FETCH_ANNOUNCEMENT_DETAIL_FAILURE = 'FETCH_ANNOUNCEMENT_DETAIL_FAILURE';

export const DOWNLOAD_ANNOUNCEMENT_FILE_SUCCESS = 'DOWNLOAD_ANNOUNCEMENT_FILE_SUCCESS';
export const DOWNLOAD_ANNOUNCEMENT_FILE_FAILURE = 'DOWNLOAD_ANNOUNCEMENT_FILE_FAILURE';


//Documents
export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';
export const FETCH_DOCUMENT_DETAIL_REQUEST = 'FETCH_DOCUMENT_DETAIL_REQUEST';
export const FETCH_DOCUMENT_DETAIL_SUCCESS = 'FETCH_DOCUMENT_DETAIL_SUCCESS';
export const FETCH_DOCUMENT_DETAIL_FAILURE = 'FETCH_DOCUMENT_DETAIL_FAILURE';
export const DOWNLOAD_DOCUMENT_REQUEST = 'DOWNLOAD_DOCUMENT_REQUEST';
export const DOWNLOAD_DOCUMENT_SUCCESS= 'DOWNLOAD_DOCUMENT_SUCCESS';
export const DOWNLOAD_DOCUMENT_FAILURE = 'DOWNLOAD_DOCUMENT_FAILURE';
export const POST_DOCUMENT_REQUEST = 'POST_DOCUMENT_REQUEST';
export const POST_DOCUMENT_SUCCESS = 'POST_DOCUMENT_SUCCESS';
export const POST_DOCUMENT_FAILURE = 'POST_DOCUMENT_FAILURE';


export const DOWNLOAD_EARNING_FILE_REQUEST = "DOWNLOAD_EARNING_FILE_REQUEST";
export const DOWNLOAD_EARNING_FILE_SUCCESS  ="DOWNLOAD_EARNING_FILE_SUCCESS";
export const DOWNLOAD_EARNING_FILE_FAILURE="DOWNLOAD_EARNING_FILE_FAILURE";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const DOWNLOAD_EXPENDITURE_FILE_REQUEST = "DOWNLOAD_EXPENDITURE_FILE_REQUEST";
export const DOWNLOAD_EXPENDITURE_FILE_SUCCESS = "DOWNLOAD_EXPENDITURE_FILE_SUCCESS";
export const DOWNLOAD_EXPENDITURE_FILE_FAILURE = "DOWNLOAD_EXPENDITURE_FILE_FAILURE";

export const UPDATE_USER_STATUS_FAILURE = "UPDATE_USER_STATUS_FAILURE";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

// actions/types.js

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

